### PR TITLE
Escape single quotes in (sqlite) string literals

### PR DESCRIPTION
**Pull request by rdwampler**
The original repo says it is no longer maintain so I am submitting the PR here. 

This fixes the problem with single quotes occurring in the file path name.

### CODE REVIEW

**Comment by sorbits** [comment]
Thanks, though I think we should use `sqlite3_bind_text` instead. Would you be willing to make that change?

**Comment by rdwampler** [comment]
Sure, if you are not in too much of a rush to get this upstream.

**Comment by rdwampler** [comment]
I updated the commit to use `sqlite3_bind_text`.

**Comment by sorbits** [comment]
Merged, thanks a lot!

**Pull request merged**
